import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en' | 'kz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    home: 'О нас',
    purchase: 'Покупка',
    rental: 'Прокат',
    contactWhatsApp: 'Связаться через WhatsApp',
    contactUs: 'Свяжитесь с нами',
    slide1Text: 'RAYDA — айда на велосипеде!',
    slide2Text: 'RAYDA — казахстанский бренд велосипедов собственного дизайна и сборки',
    slide3Text: 'RAYDA — это не просто транспорт. Это привычка жить активно',
    slide4Text: 'RAYDA подходит тем, кто хочет кататься регулярно, но без спорта на износ — в удовольствие',
    heroSlogan: 'RAYDA — движение, которое приносит удовольствие',
    heroSubtitle: 'RAYDA — казахстанский бренд велосипедов собственного дизайна и сборки.',
    heroParagraph1: 'Мы создаём велосипеды для прогулок, отдыха и активного образа жизни — для людей, которые выбирают здоровье, движение и свободу.',
    heroParagraph2: 'Наши велосипеды одинаково комфортны на городских улицах, в парках и на загородных маршрутах. RAYDA подходит тем, кто хочет кататься регулярно, но без спорта на износ — в удовольствие.',
    heroParagraph3: 'RAYDA — это не просто транспорт. Это привычка жить активно.',
    learnMore: 'Узнать больше',
    aboutBrand: 'О бренде',
    brandStory: 'Бренд создан в 2024 году казахстанскими энтузиастами велоспорта с многолетним опытом в велоиндустрии.',
    brandDevelopment: 'Конструкцию разрабатывали с учётом казахстанских дорог, климата и особенностей эксплуатации. Дизайн — свой, сборка — в Казахстане.',
    founders: 'Основатели',
    foundersTitle: 'Основатели бренда',
    founderTemirjan: 'Абдрахманов Темиржан',
    founderAidar: 'Айдар Мукей — UCI Mechanic Level 2',
    foundersDescription: 'Каждая модель RAYDA создана с учётом условий эксплуатации: изменения температуры, городских дорог, длительных прогулок и ежедневного использования',
    modelRange: 'Номенклатура моделей',
    modelMountainPro: 'RAYDA Mountain Pro',
    modelCityComfort: 'RAYDA City Comfort',
    modelSportRacing: 'RAYDA Sport Racing',
    modelEBikeSmart: 'RAYDA E-Bike Smart',
    modelDescription: 'Универсальный городской велосипед',
    ourPhilosophy: 'Наша философия',
    philosophyIntro: 'Мы верим: велосипед нужен не раз в месяц «на выходных», а регулярно — как привычка.',
    philosophyAccent1: 'Удобная посадка — чтобы не уставать',
    philosophyAccent2: 'Долговечные комплектующие — не для гонок, но и не одноразовые',
    philosophyAccent3: 'Простое обслуживание — без сложных настроек',
    philosophyAccent4: 'Универсальность — один велосипед на все задачи',
    philosophyAccent5: 'Доступная цена — без накруток за импорт и бренд',
    forWhom: 'Для кого наши велосипеды',
    forWhomFamily: 'Для семейных прогулок в парке',
    forWhomCommute: 'Для поездок на работу или учёбу',
    forWhomWeekend: 'Для выходных на природе',
    forWhomActive: 'Для тех, кто хочет больше двигаться',
    advantages: 'Преимущества RAYDA',
    advantage1Title: 'Казахстанская сборка',
    advantage1Text: 'Полный цикл контроля качества и быстрая гарантийная поддержка',
    advantage2Title: 'Продуманная конструкция',
    advantage2Text: 'Геометрия рамы и компоненты подобраны для комфорта и долговечности',
    advantage3Title: 'Честная цена',
    advantage3Text: 'Без наценок за импорт — стоимость формируется локально',
    advantage4Title: 'Надёжность',
    advantage4Text: 'Проверенные комплектующие, устойчивость к нагрузкам',
    advantage5Title: 'Универсальность',
    advantage5Text: 'Подходит для города, парка и лёгкого бездорожья',
    advantage6Title: 'Сервис',
    advantage6Text: 'Доступное обслуживание, простота ремонта',
    contactsTitle: 'Контакты',
    contactsText: 'Мы всегда открыты для сотрудничества, дилеров и партнёров.',
    aboutUs: 'О нас',
    ourMission: 'Наша миссия',
    ourValues: 'Наши ценности',
    ourHistory: 'Наша история',
    owners: 'Владельцы компании',
    howToBuy: 'Как купить',
    models: 'Наши модели',
    rentalConditions: 'Условия проката',
    bookNow: 'Забронировать',
    popularRoutes: 'Популярные маршруты',
    popularRoutesSubtitle: 'Выбирайте маршрут по душе — от спокойных городских прогулок до живописных загородных трасс',
    route1Name: 'Городской променад',
    route1Description: 'Прогулка по центральным улицам с посещением парков и набережных. Идеально для знакомства с городом',
    route2Name: 'Парковый круг',
    route2Description: 'Маршрут через три главных парка города с зонами отдыха и кафе',
    route3Name: 'Загородная тропа',
    route3Description: 'Живописная дорога вдоль леса и озера. Подходит для семейного отдыха',
    route4Name: 'Вечерний круиз',
    route4Description: 'Освещённый маршрут по городу с видами на подсвеченные здания и мосты',
    distance: 'Расстояние',
    difficulty: 'Сложность',
    easy: 'Лёгкая',
    medium: 'Средняя',
    hard: 'Сложная',
    saveRoute: 'Сохранить маршрут',
    aboutBrandFull: 'RAYDA — новый велосипедный бренд, созданный в Казахстане мастерами с многолетним практическим опытом сборки, обслуживания и ремонта велосипедов. Мы знаем велосипед не по каталогам, а по реальной эксплуатации — сотням обслуженных и восстановленных велосипедов разных производителей. Именно этот опыт позволил нам разработать собственную конструкцию, ориентированную на комфорт, надёжность и простоту обслуживания',
    philosophyText: 'Мы уверены: велосипед должен использоваться часто, а не стоять в кладовке',
    philosophySlogan: 'RAYDA — это велосипед, который не требует привыкания. Вы просто садитесь и едете',
    forWhomTitle: 'RAYDA создан для:',
    forWhomCityRides: 'Прогулок по городу',
    forWhomParks: 'Поездок в парках и на набережных',
    forWhomNature: 'Отдыха на природе',
    forWhomBeginners: 'Людей, начинающих кататься',
    forWhomHealthy: 'Любителей здорового образа жизни',
    forWhomFamilyUse: 'Семейного использования',
    forWhomConclusion: 'Это идеальный выбор для тех, кто хочет больше двигаться и проводить время на свежем воздухе',
    advantagesKzAssembly: 'Казахстанская сборка и дизайн',
    advantagesProven: 'Проверенные решения без сложных и капризных систем',
    advantagesComfort: 'Комфортная геометрия рамы',
    advantagesEasyService: 'Лёгкое обслуживание',
    advantagesDaily: 'Подходит для ежедневных поездок',
    advantagesReliability: 'Надёжность в разных погодных условиях',
    rentalLocations: 'Точки проката',
    contacts: 'Контакты',
    address: 'Адрес',
    phone: 'Телефон',
    email: 'Email',
    privacyPolicy: 'Политика конфиденциальности',
    termsOfService: 'Пользовательское соглашение',
    allRightsReserved: 'Все права защищены',
    missionText: 'Сделать велосипедный спорт доступным для каждого и продвигать здоровый образ жизни',
    valuesText: 'Качество, инновации и забота о клиентах',
    historyText: 'RAYDA — новый велосипедный бренд, запускающийся в майские праздники 2026 года',
    buyViaWhatsApp: 'Купить через WhatsApp',
    buyViaKaspi: 'Купить на Каспи Магазин',
    otherOptions: 'Другие способы покупки',
    pricePerHour: 'Цена за час',
    pricePerDay: 'Цена за день',
    workingHours: 'Время работы',
    name: 'Имя',
    phoneNumber: 'Номер телефона',
    rentalDate: 'Дата проката',
    submit: 'Отправить',
  },
  en: {
    home: 'About Us',
    purchase: 'Purchase',
    rental: 'Rental',
    contactWhatsApp: 'Contact via WhatsApp',
    contactUs: 'Contact Us',
    slide1Text: 'RAYDA — movement that brings pleasure',
    slide2Text: 'RAYDA is a Kazakhstani bicycle brand with its own design and assembly',
    slide3Text: 'RAYDA is not just transport. It is a habit of living actively',
    slide4Text: 'RAYDA is suitable for those who want to ride regularly, but without exhausting sports — for pleasure',
    heroSlogan: 'RAYDA — movement that brings pleasure',
    heroSubtitle: 'RAYDA is a Kazakhstani bicycle brand with its own design and assembly.',
    heroParagraph1: 'We create bicycles for walks, recreation and an active lifestyle — for people who choose health, movement and freedom.',
    heroParagraph2: 'Our bicycles are equally comfortable on city streets, in parks and on country routes. RAYDA is suitable for those who want to ride regularly, but without exhausting sports — for pleasure.',
    heroParagraph3: 'RAYDA is not just transport. It is a habit of living actively.',
    learnMore: 'Learn More',
    aboutBrand: 'About the Brand',
    brandStory: 'The brand was created in 2024 by Kazakhstani cycling enthusiasts with many years of experience in the cycling industry.',
    brandDevelopment: 'The design was developed taking into account Kazakhstani roads, climate and operating features. The design is our own, assembly is in Kazakhstan.',
    founders: 'Founders',
    foundersTitle: 'Brand Founders',
    founderTemirjan: 'Abdrakhmanov Temirjan',
    founderAidar: 'Aidar Mukey — UCI Mechanic Level 2',
    foundersDescription: 'Each RAYDA model is created taking into account operating conditions: temperature changes, city roads, long walks and daily use',
    modelRange: 'Model Range',
    modelMountainPro: 'RAYDA Mountain Pro',
    modelCityComfort: 'RAYDA City Comfort',
    modelSportRacing: 'RAYDA Sport Racing',
    modelEBikeSmart: 'RAYDA E-Bike Smart',
    modelDescription: 'Universal city bicycle',
    ourPhilosophy: 'Our Philosophy',
    philosophyIntro: 'We believe: a bicycle is needed not once a month "on weekends", but regularly — as a habit.',
    philosophyAccent1: 'Comfortable seating — so you don\'t get tired',
    philosophyAccent2: 'Durable components — not for racing, but not disposable',
    philosophyAccent3: 'Simple maintenance — without complex settings',
    philosophyAccent4: 'Versatility — one bicycle for all tasks',
    philosophyAccent5: 'Affordable price — without markups for import and brand',
    forWhom: 'Who Are Our Bicycles For',
    forWhomFamily: 'For family walks in the park',
    forWhomCommute: 'For commuting to work or school',
    forWhomWeekend: 'For weekends in nature',
    forWhomActive: 'For those who want to move more',
    advantages: 'RAYDA Advantages',
    advantage1Title: 'Kazakhstani Assembly',
    advantage1Text: 'Full quality control cycle and fast warranty support',
    advantage2Title: 'Thoughtful Design',
    advantage2Text: 'Frame geometry and components selected for comfort and durability',
    advantage3Title: 'Fair Price',
    advantage3Text: 'No import markups — cost is formed locally',
    advantage4Title: 'Reliability',
    advantage4Text: 'Proven components, resistance to loads',
    advantage5Title: 'Versatility',
    advantage5Text: 'Suitable for city, park and light off-road',
    advantage6Title: 'Service',
    advantage6Text: 'Affordable maintenance, easy repair',
    contactsTitle: 'Contacts',
    contactsText: 'We are always open for cooperation, dealers and partners.',
    aboutUs: 'About Us',
    ourMission: 'Our Mission',
    ourValues: 'Our Values',
    ourHistory: 'Our History',
    owners: 'Company Owners',
    howToBuy: 'How to Buy',
    models: 'Our Models',
    rentalConditions: 'Rental Conditions',
    bookNow: 'Book Now',
    popularRoutes: 'Popular Routes',
    popularRoutesSubtitle: 'Choose a route to your liking — from calm city walks to scenic country trails',
    route1Name: 'City Promenade',
    route1Description: 'A walk through the central streets with visits to parks and embankments. Perfect for getting to know the city',
    route2Name: 'Park Circle',
    route2Description: 'Route through three main city parks with rest areas and cafes',
    route3Name: 'Country Trail',
    route3Description: 'Scenic road along the forest and lake. Suitable for family recreation',
    route4Name: 'Evening Cruise',
    route4Description: 'Illuminated city route with views of lit buildings and bridges',
    distance: 'Distance',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    saveRoute: 'Save Route',
    aboutBrandFull: 'RAYDA is a new bicycle brand created in Kazakhstan by craftsmen with many years of practical experience in assembling, servicing and repairing bicycles. We know bicycles not from catalogs, but from real operation — hundreds of serviced and restored bicycles from different manufacturers. It is this experience that allowed us to develop our own design focused on comfort, reliability and ease of maintenance',
    philosophyText: 'We are sure: a bicycle should be used often, not standing in the closet',
    philosophySlogan: 'RAYDA is a bicycle that requires no getting used to. You just sit down and ride',
    forWhomTitle: 'RAYDA is created for:',
    forWhomCityRides: 'City walks',
    forWhomParks: 'Rides in parks and on embankments',
    forWhomNature: 'Recreation in nature',
    forWhomBeginners: 'People starting to ride',
    forWhomHealthy: 'Healthy lifestyle enthusiasts',
    forWhomFamilyUse: 'Family use',
    forWhomConclusion: 'This is the perfect choice for those who want to move more and spend time outdoors',
    advantagesKzAssembly: 'Kazakhstani assembly and design',
    advantagesProven: 'Proven solutions without complex and capricious systems',
    advantagesComfort: 'Comfortable frame geometry',
    advantagesEasyService: 'Easy maintenance',
    advantagesDaily: 'Suitable for daily trips',
    advantagesReliability: 'Reliability in different weather conditions',
    rentalLocations: 'Rental Locations',
    contacts: 'Contacts',
    address: 'Address',
    phone: 'Phone',
    email: 'Email',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    allRightsReserved: 'All rights reserved',
    missionText: 'Make cycling accessible to everyone and promote a healthy lifestyle',
    valuesText: 'Quality, innovation and customer care',
    historyText: 'RAYDA is a new bicycle brand launching during May holidays 2026',
    buyViaWhatsApp: 'Buy via WhatsApp',
    buyViaKaspi: 'Buy on Kaspi Shop',
    otherOptions: 'Other Purchase Options',
    pricePerHour: 'Price per hour',
    pricePerDay: 'Price per day',
    workingHours: 'Working hours',
    name: 'Name',
    phoneNumber: 'Phone Number',
    rentalDate: 'Rental Date',
    submit: 'Submit',
  },
  kz: {
    home: 'Біз туралы',
    purchase: 'Сатып алу',
    rental: 'Жалға алу',
    contactWhatsApp: 'WhatsApp арқылы байланысу',
    contactUs: 'Бізге хабарласу',
    slide1Text: 'RAYDA — ләззат әкелетін қозғалыс',
    slide2Text: 'RAYDA — өз дизайны және құрастыруы бар қазақстандық велосипед бренді',
    slide3Text: 'RAYDA — бұл тек көлік емес. Бұл белсенді өмір сүру әдеті',
    slide4Text: 'RAYDA үнемі жүргілікті қалайтындарға қолайлы, бірақ шаршатпайтын спортсыз — ләззатпен',
    heroSlogan: 'RAYDA — ләззат әкелетін қозғалыс',
    heroSubtitle: 'RAYDA — өз дизайны және құрастыруы бар қазақстандық велосипед бренді.',
    heroParagraph1: 'Біз серуендеу, демалу және белсенді өмір салты үшін велосипедтер жасаймыз — денсаулық, қозғалыс және бостандықты таңдайтын адамдар үшін.',
    heroParagraph2: 'Біздің велосипедтер қалалық көшелерде, саябақтарда және шағын маршруттарда бірдей ыңғайлы. RAYDA үнемі жүргілікті қалайтындарға қолайлы, бірақ шаршатпайтын спортсыз — ләззатпен.',
    heroParagraph3: 'RAYDA — бұл тек көлік емес. Бұл белсенді өмір сүру әдеті.',
    learnMore: 'Толығырақ',
    aboutBrand: 'Бренд туралы',
    brandStory: 'Бренд 2024 жылы велоспорт саласында көп жылдық тәжірибесі бар қазақстандық энтузиастармен құрылды.',
    brandDevelopment: 'Конструкция қазақстандық жолдар, климат және пайдалану ерекшеліктерін ескере отырып әзірленді. Дизайн — өзіміздікі, құрастыру — Қазақстанда.',
    founders: 'Құрылтайшылар',
    foundersTitle: 'Бренд құрылтайшылары',
    founderTemirjan: 'Абдрахманов Темиржан',
    founderAidar: 'Айдар Мукей — UCI Mechanic Level 2',
    foundersDescription: 'Әрбір RAYDA моделі пайдалану жағдайларын ескере отырып жасалады: температура ауытқулары, қалалық жолдар, ұзақ серуендер және күнделікті пайдалану',
    modelRange: 'Модельдер қатары',
    modelMountainPro: 'RAYDA Mountain Pro',
    modelCityComfort: 'RAYDA City Comfort',
    modelSportRacing: 'RAYDA Sport Racing',
    modelEBikeSmart: 'RAYDA E-Bike Smart',
    modelDescription: 'Әмбебап қалалық велосипед',
    ourPhilosophy: 'Біздің философия',
    philosophyIntro: 'Біз сенеміз: велосипед айына бір рет "демалыс күндері" емес, үнемі қажет — әдет ретінде.',
    philosophyAccent1: 'Ыңғайлы отыру — шаршамау үшін',
    philosophyAccent2: 'Ұзақ қызмет ететін компоненттер — жарысқа емес, бірақ бір реттік емес',
    philosophyAccent3: 'Қарапайым қызмет көрсету — күрделі баптаусыз',
    philosophyAccent4: 'Әмбебаптық — барлық міндеттерге бір велосипед',
    philosophyAccent5: 'Қолжетімді баға — импорт және бренд үшін үстемесіз',
    forWhom: 'Біздің велосипедтер күмге арналған',
    forWhomFamily: 'Саябақта отбасылық серуендеуге',
    forWhomCommute: 'Жұмысқа немесе оқуға баруға',
    forWhomWeekend: 'Табиғатта демалыс күндеріне',
    forWhomActive: 'Көбірек қозғалғысы келетіндерге',
    advantages: 'RAYDA артықшылықтары',
    advantage1Title: 'Қазақстандық құрастыру',
    advantage1Text: 'Толық сапа бақылау циклі және жылдам кепілдік қолдау',
    advantage2Title: 'Ойластырылған конструкция',
    advantage2Text: 'Жақтау геометриясы және ыңғайлылық пен берік қызметке арналған компоненттер',
    advantage3Title: 'Әділ баға',
    advantage3Text: 'Импорттық үстемелерсіз — құн жергілікті қалыптасады',
    advantage4Title: 'Сенімділік',
    advantage4Text: 'Тексерілген компоненттер, жүктемеге төзімділік',
    advantage5Title: 'Әмбебаптық',
    advantage5Text: 'Қала, саябақ және жеңіл жол жоқ жерлерге қолайлы',
    advantage6Title: 'Қызмет',
    advantage6Text: 'Қолжетімді қызмет көрсету, жөндеу оңайлығы',
    contactsTitle: 'Байланыстар',
    contactsText: 'Біз әрқашан ынтымақтастыққа, дилерлерге және серіктестерге ашықпыз.',
    aboutUs: 'Біз туралы',
    ourMission: 'Біздің миссия',
    ourValues: 'Біздің құндылықтар',
    ourHistory: 'Біздің тарих',
    owners: 'Компания иелері',
    howToBuy: 'Қалай сатып алуға болады',
    models: 'Біздің модельдер',
    rentalConditions: 'Жалға алу шарттары',
    bookNow: 'Брондау',
    popularRoutes: 'Танымал маршруттар',
    popularRoutesSubtitle: 'Жанға жайлы маршрутты таңдаңыз — тыныш қалалық серуендерден бастап сұлу шалғындық маршруттарға дейін',
    route1Name: 'Қалалық гезіт',
    route1Description: 'Саябақтар мен жағалауларға барумен орталық көшелермен серуендеу. Қаламен танысу үшін керемет',
    route2Name: 'Саябақ айналымы',
    route2Description: 'Демалыс аймақтары мен кафелері бар қаланың үш негізгі саябағы арқылы маршрут',
    route3Name: 'Шалғындық жол',
    route3Description: 'Орман мен көл бойындағы сұлу жол. Отбасылық демалысқа қолайлы',
    route4Name: 'Кешкі круиз',
    route4Description: 'Жарықтандырылған ғимараттар мен көпірлер көрінісімен қала маршруты',
    distance: 'Қашықтық',
    difficulty: 'Қиындық',
    easy: 'Оңай',
    medium: 'Орташа',
    hard: 'Қиын',
    saveRoute: 'Маршрутты сақтау',
    aboutBrandFull: 'RAYDA — велосипедтерді құрастыру, қызмет көрсету және жөндеу бойынша көп жылдық тәжірибесі бар шеберлермен Қазақстанда құрылған жаңа велосипед бренді. Біз велосипедті каталогтардан емес, нақты пайдаланудан білеміз — әртүрлі өндірушілердің жүздеген қызмет көрсетілген және қалпына келтірілген велосипедтері. Дәл осы тәжірибе бізге ыңғайлылыққа, сенімділікке және қызмет көрсетудің қарапайылығына бағытталған өз дизайнымызды әзірлеуге мүмкіндік берді',
    philosophyText: 'Біз сенеміз: велосипед жиі пайдаланылуы керек, шкафта тұрмай',
    philosophySlogan: 'RAYDA — бұл үйренуді қажет етпейтін велосипед. Сіз тек отырып, жүресіз',
    forWhomTitle: 'RAYDA мыналар үшін жасалған:',
    forWhomCityRides: 'Қалада серуендеуге',
    forWhomParks: 'Саябақтарда және жағалауда жүруге',
    forWhomNature: 'Табиғатта демалуға',
    forWhomBeginners: 'Жаңадан жүруді бастаушыларға',
    forWhomHealthy: 'Салауатты өмір салтын ұнататындарға',
    forWhomFamilyUse: 'Отбасылық пайдалануға',
    forWhomConclusion: 'Бұл көбірек қозғалғысы және ашық ауада уақыт өткізгісі келетіндер үшін тамаша таңдау',
    advantagesKzAssembly: 'Қазақстандық құрастыру және дизайн',
    advantagesProven: 'Күрделі және ерекше жүйелерсіз тексерілген шешімдер',
    advantagesComfort: 'Ыңғайлы жақтау геометриясы',
    advantagesEasyService: 'Оңай қызмет көрсету',
    advantagesDaily: 'Күнделікті сапарларға қолайлы',
    advantagesReliability: 'Әртүрлі ауа райы жағдайларында сенімділік',
    rentalLocations: 'Жалға беру нүктелері',
    contacts: 'Байланыстар',
    address: 'Мекенжай',
    phone: 'Телефон',
    email: 'Email',
    privacyPolicy: 'Құпиялылық саясаты',
    termsOfService: 'Пайдаланушы келісімі',
    allRightsReserved: 'Барлық құқықтар қорғалған',
    missionText: 'Велосипед спортын әркімге қолжетімді ету және салауатты өмір салтын насихаттау',
    valuesText: 'Сапа, инновация және клиенттерге қамқорлық',
    historyText: 'RAYDA — 2026 жылдың мамыр мерекелерінде іске қосылатын жаңа велосипед бренді',
    buyViaWhatsApp: 'WhatsApp арқылы сатып алу',
    buyViaKaspi: 'Каспи Магазинде сатып алу',
    otherOptions: 'Басқа сатып алу тәсілдері',
    pricePerHour: 'Сағаттық баға',
    pricePerDay: 'Күндік баға',
    workingHours: 'Жұмыс уақыты',
    name: 'Аты',
    phoneNumber: 'Телефон нөмірі',
    rentalDate: 'Жалға алу күні',
    submit: 'Жіберу',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ru] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}